### ISSUE TITLE
Just an idea

### ISSUE THREAD

**Issue by t-900-a** [lalanza808/xmrauctions#4]
If you want to pick up this project there is an alternative, so you don't have to rebuild ebay from scratch...

Help build this project out to support monero: https://github.com/t-900-a/odoo-solana-payments
https://www.reddit.com/r/Monero/comments/jvu81r/any_new_python_developers_who_have_joined_the/

And then people who want to have an auction house they can use odoo ecommerce and have the monero payment acquirer be enabled:

https://store.webkul.com/Odoo-Website-Auction.html

**Comment by lalanza808** [comment]
Thanks for the heads up.
